# Generated by Django 4.2.30 on 2026-08-10 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('gpio_pin', models.PositiveSmallIntegerField(unique=True)),
                ('ingredient_name', models.CharField(blank=True, default='', max_length=100)),
                ('ml_per_second', models.FloatField(default=1.6666666666666667)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ml', models.FloatField()),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pumps.pump')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='pumps.recipe')),
            ],
            options={
                'ordering': ['pump__number'],
                'unique_together': {('recipe', 'pump')},
            },
        ),
    ]
