# Generated by Django 4.2.30 on 2026-08-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0002_seed_pumps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['step', 'pump__number']},
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
